# Generated by Django 4.1.10 on 2023-08-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dish',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
