# Generated by Django 4.1.10 on 2023-08-15 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zomato', '0005_remove_purchase_dish_remove_purchase_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='selected_items',
            field=models.JSONField(),
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zomato.dish')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zomato.purchase')),
            ],
        ),
    ]
